title: Manikesh-Blog
description: "A Jekyll Blog Theme For Hackers"
author:
  name: "x71n0"
  email: "offsecmanikesh@gmail.com"
  url: "https://manikeshhhh.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "SomeHacker"
year : "2020"
